### PR TITLE
Coordinate transformation for silhouette cameo, and some minor refactoring.

### PR DESCRIPTION
**Pull request by jnweiger**
Please review and merge

### CODE REVIEW

**Comment by nosliwneb** [comment]
sorry for the delay, I've been traveling...

**Comment by mscalone** [comment]
Hello. 
any idea why seg fault on ubuntu 12.10 with Silouette Portrait?

Thanks!

---

Reading file:  "/tmp/pruReading file:  "/tmp/prueba.svg" 
SVG default size:  QSize(744, 1052) 

SVG view box:  QRectF(0,0 744.094x1052.36) 

Page size (mm):  QSizeF(210, 297) 

in path: 405.126
Sort outpath: 400.58
TSPSort outpaths: 475.611 Groups 1
TSPSort outpath sort: 475.611 Groups 1
Cutting... VENDOR_ID : 2893 PRODUCT_ID: 4381 mediawidth: 210 mediaheight: 297media: 102 speed: 10 pressure: 10 trackenhancing: 0 regmark: 0 regsearch:1 regwidth:180 reglength: 240
eba.svg" Reading file:  "/tmp/prueba.svg" 
SVG default size:  QSize(744, 1052) 

SVG view box:  QRectF(0,0 744.094x1052.36) 

Page size (mm):  QSizeF(210, 297) 

in path: 405.126
Sort outpath: 400.58
TSPSort outpaths: 475.611 Groups 1
TSPSort outpath sort: 475.611 Groups 1
Cutting... VENDOR_ID : 2893 PRODUCT_ID: 4381 mediawidth: 210 mediaheight: 297media: 102 speed: 10 pressure: 10 trackenhancing: 0 regmark: 0 regsearch:1 regwidth:180 reglength: 240

SVG default size:  QSize(744, 1052) 

SVG view box:  QRectF(0,0 744.094x1052.36) 

Page size (mm):  QSizeF(210, 297) 

in path: 405.126
Sort outpath: 400.58
TSPSort outpaths: 475.611 Groups 1
TSPSort outpath sort: 475.611 Groups 1

## Cutting... VENDOR_ID : 2893 PRODUCT_ID: 4381 mediawidth: 210 mediaheight: 297media: 102 speed: 10 pressure: 10 trackenhancing: 0 regmark: 0 regsearch:1 regwidth:180 reglength: 240

Identification menu item outputs this on terminal:

---

Fontconfig warning: "/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from ~/.fonts.conf is deprecated.
Robocut V1.0.10_jw1
Identify: usb=2893/4387 no device found

---

**Comment by nosliwneb** [comment]
What is the sequence of events leading up to the seg fault? When you plug in the plotter and run dmesg, what do the last few lines look like? Or try 'dmesg|grep vid' to find the interesting area.

**Comment by mscalone** [comment]
Hi! thanks for the quick response!

Fortunately the problem disappear after reboot, strange. Tested again after
restart and worked great..
I haven't tested the registration marks option yet. But cutting worked very
good.

Thanks.

2013/9/12 nosliwneb notifications@github.com

**Comment by jnweiger** [comment]
mscalone: probably your system was in an inconsistent state due to some partially done update, or you were extremely low on memory, or something, just guessing....

**Pull request merged**
